### ISSUE TITLE
download file from the website

### ISSUE THREAD

**Issue by JiawenChenn** [luoyuanlab/SOAR#1]
Hi authors,

Thanks for the great work! The website is super useful. I am wondering if there is a way to download the data efficiently instead of doing each slide manually in the data browser. Thanks!

**Comment by kestrel614** [comment]
> Hi authors,
> 
> Thanks for the great work! The website is super useful. I am wondering if there is a way to download the data efficiently instead of doing each slide manually in the data browser. Thanks!

Hi Jiawen,
 
Thank you for your interest in our website! Our paper is currently under review, and all the raw/processed datasets will be available for download in one place (under the "Download" tab) upon manuscript publication.
